### ISSUE TITLE
Global Engine Config

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#10]
Write a class which loads the engine config from a file from which you can access different engine config values.

**Comment by JFrap** [comment]
Currently, its loaded on startup. Ill fix it.

**Comment by JFrap** [comment]
@unpause i presume its a class with a bunch of static variables?

**Comment by unpause** [comment]
yeah which get loaded on startup. but i will change that later but that will work for now

**Comment by JFrap** [comment]
Very well. ill get onto that.

**Comment by JFrap** [comment]
@unpause i presume a "loadGlobalsFromScript" would also be static...?

**Comment by JFrap** [comment]
Added "Globals.h"
