### ISSUE TITLE
When should we go about other API implementations?

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#12]
I think that once we get all the graphical stuff working (Shadows, deffered rendering, etc...) Then we can get directx and/or vulkan working in one swoop.

**Comment by unpause** [comment]
yes we should do it like that. First implement one robust rendering API which works and then go on with other apis. 

Same goes with platform specific stuff. First windows and then mac and linux.

**Comment by unpause** [comment]
Some things will be wrappeed into object oriented classes ... but we dont want bad performance so the performance critical stuff wont be wrapped into classes.
