### ISSUE TITLE
Working on UI, need a name for "Prefabs"

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#13]
Im doing kind-of the same system as unity. You add scripts/components to an object and add them to the UI as an object you can use again.  Not sure what to call these "Prefabs" though

**Comment by unpause** [comment]
Suggestions:
Prefab
UI Blueprint

or what do you mean exactly?

**Comment by JFrap** [comment]
Like the unity prefabs.

**Comment by unpause** [comment]
template or draft

**Comment by JFrap** [comment]
Template seems good

**Comment by unpause** [comment]
i like draft more but ok xD

**Comment by unpause** [comment]
closing this issue.
