### ISSUE TITLE
License

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#14]
We should choose a license for the engine and content.

**Comment by JFrap** [comment]
Presumably open source?

**Comment by unpause** [comment]
yes, i have a good website : http://choosealicense.com/licenses/

**Comment by JFrap** [comment]
MIT seems decent

**Comment by unpause** [comment]
what about apache 2.0

**Comment by JFrap** [comment]
either which

**Comment by unpause** [comment]
go with MIT ^^

**Comment by unpause** [comment]
We need to add the small license text to every file then.
