### ISSUE TITLE
Having some issues compiling 

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#15]
Added all the include paths and such to the project settings but now im getting a "Cannot open file 'lua53.lib" Triple-checked and still complaining.

**Comment by JFrap** [comment]
Switched to release and thats working, now xcopy's showing its face.

**Comment by unpause** [comment]
I will fix the xcopy issue and i'll fix the debug configuration

**Comment by JFrap** [comment]
Very well

**Comment by JFrap** [comment]
@unpause i think i found a fix, where is the xcopy command found?

**Comment by unpause** [comment]
how do you mean where is it found? if you wanna change it look into project settings buildevents (or whatever) post build
btw i know the fix... just delete the destination folder before executing it

**Comment by JFrap** [comment]
ok

**Comment by unpause** [comment]
Added debug configuration and fixed xcopy bug with commit b5b4c256

**Comment by JFrap** [comment]
@unpause not seeing that commit yet (probably just me)

**Comment by JFrap** [comment]
nvm, got it

**Comment by JFrap** [comment]
@unpause lib folder missing...?

**Comment by unpause** [comment]
lol why is it missing

**Comment by JFrap** [comment]
You removed it in the latest commit

**Comment by JFrap** [comment]
But didnt add it back

**Comment by unpause** [comment]
oh i know why
.gitignore ignores x86 and x64... fixed

**Comment by unpause** [comment]
will fix it .gitignore ignores x86 folders.

**Comment by JFrap** [comment]
ahh

**Comment by unpause** [comment]
our commits are a mess

**Comment by unpause** [comment]
finally fixed with commit  6d898a7

**Comment by JFrap** [comment]
Xcopy strikes again?

**Comment by JFrap** [comment]
Xcopy doesnt really hinder compilation. It just likes attention

**Comment by unpause** [comment]
what does it say?
