### ISSUE TITLE
Should frame buffers have a function that lets them draw to the screen?

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#17]

**Comment by unpause** [comment]
no let the renderer do that

**Comment by unpause** [comment]
we should create some collaboration chat so we dont have to spam our issues with stuff like this

**Comment by JFrap** [comment]
yea

**Comment by JFrap** [comment]
https://teazel-engine.slack.com/messages/general/

**Comment by JFrap** [comment]
@unpause The renderer will call the function and dictate whether an object will render to it or not.

**Comment by unpause** [comment]
you need to invite me @JFrap my email is roidl.sebastian@gmail.com (will get deleted after you invited me :P)
