### ISSUE TITLE
Framebuffers *STILL* not working

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#19]
If you comment out glDeleteFrameBuffers in FrameBuffer.h it- all of a sudden works.

**Comment by unpause** [comment]
we need to render the framebuffer to see if it really works.

**Comment by JFrap** [comment]
yea

**Comment by JFrap** [comment]
@unpause can you try getting the frame buffer class working? i dont know what im doing at this point.

**Comment by unpause** [comment]
rewrote framebuffer classes. we just need to do something to render the framebuffer which you just do by rendering the framebuffer image onto a quad or something.

**Comment by JFrap** [comment]
@unpause good, cant be too difficult.

**Comment by unpause** [comment]
you can do it if you want

**Comment by unpause** [comment]
Result for me: bind buffers -> black screen; not binding buffers -> rendering

**Comment by unpause** [comment]
Now: Framebuffer is displayed but vertices are not rendered.

**Comment by unpause** [comment]
Now: Everything is rendered to the framebuffer but the framebuffer is not displayed onto the screen.

**Comment by unpause** [comment]
maybe we use something opengl 4 related in the shader or somewhere

**Comment by unpause** [comment]
They atleast render a bit now
but i just have two black things on the screen

**Comment by unpause** [comment]
Fixed with  5738de6
