### ISSUE TITLE
Color buffer creation and rendering bug.

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#20]
This happens when you enable the wrapped code in GameObject this happens: 

![image](https://cloud.githubusercontent.com/assets/9016634/16562553/d8ba7bba-41fd-11e6-8b53-8fafb49c3f53.png)

**Comment by unpause** [comment]
Now there is just no color at all.

**Comment by JFrap** [comment]
Ouch, what happened here?

**Comment by unpause** [comment]
i dont know. the vertices are still rendered but not the colors.

**Comment by unpause** [comment]
Fixed with ca7b3ec
