### ISSUE TITLE
Currently unable to set data format (RGBA**16F**, etc)

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#23]

**Comment by unpause** [comment]
data format for what?

**Comment by JFrap** [comment]
Like 16 bit or 32 bit floats, for example

**Comment by unpause** [comment]
for what? textures? what do you mean?

**Comment by JFrap** [comment]
yep

**Comment by unpause** [comment]
you can. use the TextureParameters argument in the texture create function. look at the framebuffer init functions... its done there

**Comment by unpause** [comment]
Fixed with  3387930
