### ISSUE TITLE
GameObject cant have more than one component

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#24]
If i add another component, it will spit "... undefined variable" in the console

**Comment by JFrap** [comment]
Fixed this, but now the first component you add simply doesnt update.

**Comment by unpause** [comment]
what about this issue? is this fixed? @JFrap

**Comment by unpause** [comment]
This will probably be resolved with the new ECS.

**Comment by unpause** [comment]
I will close this for now because we dont have the system anymore.
