### ISSUE TITLE
Low precision frame buffers(resulting in this effect)

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#27]
http://imgur.com/HsKhd0P

**Comment by unpause** [comment]
you mean low resolution?

**Comment by JFrap** [comment]
@unpause Nope, precision. i require atleast a 16 bit color buffer

**Comment by unpause** [comment]
oh you mean that.. um yeah i will look into that if you dont do already

**Comment by JFrap** [comment]
@unpause i had ago at changing it, but it really _*really*_ didnt like it

**Comment by JFrap** [comment]
sort-of fixed
