### ISSUE TITLE
Implement a nice scene hierarchy.

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#3]
We need to implement a good scene hierarchy that works well with a lot of games where you can organize your scenes in a nice way. 

A lot of games use a Entity Component System based approach. But there are some engines like the Godot Engine which use a Node based approach.

Lets discuss on this.

- [x] GameObjects
- [x] Components
- [ ] Systems
- [ ] Custom components via Scripting

**Comment by JFrap** [comment]
Currently, its main->scene->renderer. I think ill call the object's update function(that calles the lua) in a seperat thread.

**Comment by JFrap** [comment]
I imagine we can go component based. Maybe each component will have its own lua script?

**Comment by unpause** [comment]
yes very much like unity

**Comment by unpause** [comment]
we should also consider that we eventually want to save the scenes as a data file later on. so the scenetree needs to be serializable in a good way.

**Comment by JFrap** [comment]
@unpause I was thinking about that. We could probably use with a sort of internal file system too.

**Comment by unpause** [comment]
I think component based is still the best method to do the scene tree. I think we will go with this.

**Comment by JFrap** [comment]
"Custom components via scripting" So, creating components script-side?

**Comment by unpause** [comment]
yes

**Comment by unpause** [comment]
This is done now with the new ECS.
