### ISSUE TITLE
"LNK1181 cannot open input file 'C:\Users\[my name]\Documents\GitHub\TeazelEngine\TeazelEngine\Release\SamplePlugin.dll"

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#30]
damn linker errors

**Comment by unpause** [comment]
its because it gets deleted sometime in the build process just buils the solution and then build the sampleplugin on itself

**Comment by JFrap** [comment]
Very well, @unpause i added an inverse function. Oh, and it looks _*really*_ messed up when running,

**Comment by unpause** [comment]
thats atleast what i think why it happens

**Comment by JFrap** [comment]
@unpause ?

**Comment by unpause** [comment]
@JFrap yeah i wanted you to take a look at it... its something with the matrices wrong or so...

**Comment by JFrap** [comment]
ok

**Comment by unpause** [comment]
probably the view matrix which is wrong

**Comment by JFrap** [comment]
yea

**Comment by JFrap** [comment]
ive tried some stuff with the view matrix, still not working

**Comment by unpause** [comment]
hm ok i am going to look into it tommorrow just use glm for now after we fixed the matrix stuff we can get rid of glm

**Comment by unpause** [comment]
btw i dont get that error
