### ISSUE TITLE
Camera movement is partially broken when using our own vec3 class.

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#33]
The camera movement is broken when we use our vector class instead of the glm::vec3. It moves ok on the either the X or Z axis but it moves on like a slope on one of those axes. Also the direction in which you are looking has no influence in where you are moving.

It was probably some mistake on how we handled converting the vectors and so on but this issue is still worth keeping if something like this happens again.

**Comment by JFrap** [comment]
For me, it rotates fine but it just doesnt move.

**Comment by unpause** [comment]
pull the newest commit. the movement is fixed there

**Comment by unpause** [comment]
This was probably and issue on how we synchronized the values. Will be closing this now.
