### ISSUE TITLE
Dont upload .exe files and build files to the git repo.

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#4]

**Comment by JFrap** [comment]
hm, so upload only the relevant source code?

**Comment by unpause** [comment]
exactly.

- makes pushing and pulling faster
- removes unnessesary commits and files
- and git doesnt work well with binary files.

**Comment by JFrap** [comment]
Very well

**Comment by unpause** [comment]
Closed with commit 7ab366e
