### ISSUE TITLE
Abstract actual API implementation from the code you use.

### ISSUE THREAD

**Issue by unpause** [JFrap/TeazelEngine#6]
Abstract code away from API specific code for example opengl.
I mean it like this:

auto shader = Shader::Create() -> if opengl return new OpenGLShader() if d3d return new D3DShader()
shader.SetVar<mat4>("mvp", mvp); // works for d3d and opengl the same then and we have some abstraction

Same goes with physics implementations.
Same goes with audio implementations.
Same goes with scripting languages.

**Comment by JFrap** [comment]
Hm, multiple API implementations?

**Comment by JFrap** [comment]
Maybe SFML can do Directx, otherwise we must create our own windowing class. Maybe the API can be dictated in EngineInfo.lua?

**Comment by unpause** [comment]
in the direct3d case sfml only serves for window creation. context creation is other than opengl done with the DirectX api itself (same goes for vulkan).

**Comment by JFrap** [comment]
Very well.

**Comment by JFrap** [comment]
Directx 11 i presume?

**Comment by unpause** [comment]
yes d3d11 ... because it works everywhere. even on older d3d versions if you dont use the very specific only d3d11 stuff. you just need to ship the newer compiler dll with the engine so older drivers can compile the newer shaders.

**Comment by JFrap** [comment]
Alrighty,

**Comment by JFrap** [comment]
I presume your working on this, considering you actually know Directx

**Comment by JFrap** [comment]
Ill *try* to find something to read on it.

**Comment by unpause** [comment]
This is almost done now.

**Comment by unpause** [comment]
Mostly done. Just some exceptions for example in Renderer3D which will get sorted because of different Renderer types which implementation will start soon.

Closing with  8e2eb23
