### ISSUE TITLE
General "What are you working on" discussion

### ISSUE THREAD

**Issue by JFrap** [JFrap/TeazelEngine#7]
Currently working on lighting

**Comment by unpause** [comment]
Lets create Trello for that.

**Comment by JFrap** [comment]
Yea, ill get onto that

**Comment by JFrap** [comment]
@unpause whats your trello name?

**Comment by JFrap** [comment]
@unpause nvm, https://trello.com/invite/b/ZfjwMz4L/624192668e041981cb4fe6eb3c183eb8/teazelengine
